sudo: false
language: python
python:
  - 3.7

cache:
  - pip

install: pip install -r ./requirements.txt

script:
  - make test
  - make check

after_success:
  - codecov

notifications:
  slack: ash84:XLALpV0b20grjYRBYJ9ooVaE
