sudo: false
language: python
python:
  - "3.6"
  - "3.7-dev"
before_script:
  - flake8 --count --exclude ./tests,./doc --ignore E402,F401,E501
install: pip install -r ./requirements.txt
script:
  - pytest -s -v
  - flake8 --count --exclude ./tests --ignore E402,F401,E501
cache: pip