name: CD

on:
  push:
    branches:
      - master
    tags:
      - 1.*
      - 2.*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Docker Build
      run: |
        docker build --tag ash84/meier:${{ github.ref }} .


