name: CD

on:
  push:
    tags:
      - 1.*
      - 2.*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: TEST
        run: |
          BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g" | sed -e "s/\//-/g")
          echo ${GITHUB_REF}
          echo $BRANCH

#      - name: Publish to Registry
#        uses: elgohr/Publish-Docker-Github-Action@master
#        with:
#          name: ash84/meier
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
