name: CD

on:
  push:
    branches:
      - master
    tags:
      - 1.*
      - 2.*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        login-server: index.docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - run: |
        tag=$(cut -d"/" -f3<<<"${{ github.ref }}")
        docker build . -t ash84/meier:$tag
        docker push ash84/meier:$tag
