name: CD

on:
  push:
    branches:
      - master
    tags:
      - 1.*
      - 2.*

jobs:

  build-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: |
        tag=$(cut -d"/" -f3<<<"${{ github.ref }}")
        docker build --tag ash84/meier:$tag .
    - name: Docker Push
      uses: opspresso/action-docker@master
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        IMAGE_NAME: "ash84/meier"
        TAG_NAME: $tag
