name: CD

on:
  push:
    branches:
      - master
    tags:
      - 1.*
      - 2.*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker Build
      run: |
        tag=$(cut -d"/" -f3<<<"${{ github.ref }}")
        docker build --tag ash84/meier:$tag .

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Publish
      run: |
        tag=$(cut -d"/" -f3<<<"${{ github.ref }}")
        echo '${{secrets.DOCKER_HUB_USER_PASSWORD}}' | docker login -u ${{secrets.DOCKER_HUB_USER_NAME}} --password-stdin
        docker push ash84/meier:$tag





