name: CD(prod-build)

on:
  push:
    tags:
      - 2021.*
      - 2022.*
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get the version from Tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        env:
          REPOSITORY: ash84/meier
          IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}
        run: |
          docker build \
          --build-arg DB_HOST=${{ secrets.DB_HOST }} \
          --build-arg DB_USER=${{ secrets.DB_USER }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME }} \
          --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
          -t $REPOSITORY:$IMAGE_TAG .
          docker push $REPOSITORY:$IMAGE_TAG
          docker tag $REPOSITORY:$IMAGE_TAG $REPOSITORY:latest
          docker push $REPOSITORY:latest
