name: CI

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    container:
      image: python:3.7.3-slim-stretch
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y gcc make  build-essential
        pip install -U pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: TEST
      run: |
        make test
    - name: CHECK
      run: |
        make check
