name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: TEST
      run: |
        python -m pytest
    - name: CHECK
      run: |
        isort --recursive --check-only meier wsgi.py
        black -l 79 --check meier wsgi.py
        pylint meier wsgi.py
   - name: COVERAGE
      run: |
        codecov
